"""
Parental-leave generosity index (broad bundle, full-rate-equivalent weeks).

For each (cao_number, id) record in inputs/extracted_data_non_salary.csv,
computes a per-record family-leave generosity index combining maternity,
paternity/partner, adoption, and parental top-up leave into a single
"full-rate-equivalent (FRE) weeks" number.

FRE per leave-type = paid_weeks * 1.00
                   + partially_paid_weeks * (replacement_rate / 100)
                   + unpaid_weeks * 0.00

The index sums FRE across the four leave types.

Two versions are output:
  fre_total_extracted   : sum of what is EXPLICITLY recorded in the CAO
                          (no statutory imputation).
  fre_total_with_statutory: max(extracted, statutory_floor_at_ingangsdatum)
                          per type, then summed. Closer to the actual
                          family-leave package the worker receives.

Companion variables exported alongside the indices, per leave type:
  *_weeks_total : total job-protected weeks (paid + partially_paid + unpaid)
  *_fre         : full-rate equivalent weeks for that type
  *_imputed     : True if statutory floor was used instead of extracted

Units handled:
  Duration units normalised to weeks (DAY=0.2 wks, MONTH=4.333 wks,
  YEAR=52 wks, the various "weekly working hours" / "FTE-equivalent"
  variants treated as weeks ×1).
  Pay-rate units treated as percent of own wage (statutory benefit caps
  ignored - matches the OECD full-rate equivalent convention).

Output: indices/out/parental_leave_index.csv (one row per record).

Run:
  python3 qa/indices/parental_leave_index.py
"""
from __future__ import annotations
import os
import re
import sys
from datetime import date, datetime
from pathlib import Path
import pandas as pd

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import index_lib as il  # v2: file_date axis, pooled z, params persistence

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
HERE = Path(__file__).resolve().parent
PROJECT_ROOT = HERE.parent  # indices/ is now a top-level dir (moved from qa/indices/)
# Canonical source is the QA-corrected dataset (qa/corrected_dataset.csv),
# not the raw extract. NOTE: corrected_dataset.csv applies only the 11
# non-leave topics' corrections (qa/apply_list.csv has 0 leave edits), so it
# is byte-identical to inputs/extracted_data_non_salary.csv on every leave_*
# field — the parental-leave output is unchanged vs the raw extract. The
# qa_leave corrections were reviewed and rejected, so they are NOT applied.
INPUT_CSV = PROJECT_ROOT / "qa" / "corrected_dataset.csv"
OUTPUT_CSV = Path(il.OUT) / "parental_leave_index.csv"
OUTPUT_DIAGNOSTICS = Path(il.OUT) / "parental_leave_index_diagnostics.csv"
# Source-verified leave-field corrections applied on top of corrected_dataset.csv
# (see leave_source_corrections.csv for the per-cell evidence). These are leave
# fixes derived from reading the CAO source text directly; they are kept as an
# index-local overlay rather than in qa/apply_list.csv because the leave topic
# is outside the non-leave QA pipeline and apply_list.csv is regenerated by
# consolidate_review.py (which would clobber them).
LEAVE_CORRECTIONS_CSV = Path(il.locate("leave_source_corrections.csv"))  # audit-trail overlay -> corrections/

# ---------------------------------------------------------------------------
# Unit conversion helpers
# ---------------------------------------------------------------------------
WEEK = 1.0
DAY  = 1.0 / 5.0       # 5 working days per week
MONTH = 13.0 / 3.0     # 4.333 weeks
YEAR = 52.0

# Use word-boundary anchored patterns so e.g. "monthly" inside "% of monthly
# salary" does NOT match the months pattern. Order matters: weeks first, then
# days, months, years.
DURATION_KEYWORDS = (
    (re.compile(r"\bweek(s|ly)?\b", re.I),               WEEK),  # weeks, week, weekly (working hours)
    (re.compile(r"\bwork\s*weeks?\b", re.I),             WEEK),  # workweek/workweeks (no space breaks \bweek\b)
    (re.compile(r"\bweekly[_\s]*working", re.I),         WEEK),  # weekly_working_hours (underscore breaks \bweek\b)
    (re.compile(r"\b(working\s*)?days?\b", re.I),        DAY),
    (re.compile(r"\bwork\s*days?\b", re.I),              DAY),   # workday/workdays (no space)
    (re.compile(r"\bdays?/shifts?\b", re.I),             DAY),
    (re.compile(r"\b(shifts?|services?)\b", re.I),       DAY),   # a shift/service ~ one worked day
    (re.compile(r"\bmonths?\b", re.I),                   MONTH),
    (re.compile(r"\byears?\b", re.I),                    YEAR),
    (re.compile(r"\bhours?\b", re.I),                    None),  # bare hours: ambiguous; fall back to statutory
)

# leave COVERAGE booleans (the 9 parental/holiday-leave generosity flags; the 3 sickness/care
# top-ups moved to absence on 2026-07-08). Module-level so introspection (advanced_analysis
# factor/FAMD analysis via getattr(module, "BOOLEANS")) can find them — the coverage share in
# main() is built from this same list.
BOOLEANS = [
    "leave_has_leave_enhancements", "leave_has_above_statutory_maternity",
    "leave_paternity_explicitly_above_statutory", "leave_parental_eligibility_present",
    "leave_parental_topup_present", "leave_abortion_present",
    "leave_liberation_day_annual", "leave_liberation_day_lustrum", "leave_extra_seniority_present",
]

PAY_PCT_RE = re.compile(r"%|percent", re.I)
# A unit string that begins with a percent token (possibly after a leading
# float/int — but in practice the value column holds the number, so the unit
# starts with %/percent) is treated as a pay-rate that the extractor put in
# the duration field. "weeks at 100% pay" does NOT match — % is not at start.
PAY_PCT_LEADING_RE = re.compile(r"^\s*(%|percent(?![a-z]))", re.I)


def parse_float(x):
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return None
    s = str(x).strip()
    if not s:
        return None
    try:
        return float(s.replace(",", "."))
    except ValueError:
        return None


def _safe_str(x):
    if x is None or (isinstance(x, float) and pd.isna(x)):
        return ""
    return str(x).strip()


def duration_to_weeks(value, unit) -> float | None:
    """Convert (value, unit) to weeks. Returns None if not parseable.

    IMPORTANT: if the unit string contains a percent token AND no duration
    token, the value is almost certainly a pay-RATE that the extractor
    mis-stored in the duration field (e.g. unit='% of monthly salary',
    value=100). In that case duration is unknown — return None so the
    defensive imputation downstream can kick in (statutory duration @ rate).

    But if the unit contains BOTH a duration token AND a percent token
    (e.g. "weeks at 100% pay"), trust the duration parse.
    """
    v = parse_float(value)
    if v is None:
        return None
    u = _safe_str(unit)
    if not u:
        return None
    # If the unit STARTS with a percent token (e.g. "% of monthly salary
    # for 1st year"), it's a misplaced pay rate, not a duration — even if
    # a downstream duration word appears decoratively.
    if PAY_PCT_LEADING_RE.match(u):
        return None
    for rx, mult in DURATION_KEYWORDS:
        if rx.search(u):
            return None if mult is None else v * mult
    if PAY_PCT_RE.search(u):
        return None  # pay rate stored in duration field; duration unknown
    return None  # unknown unit -> flag as None


def pay_rate(value, unit) -> float | None:
    """Convert pay (value, unit) to a 0-1 fraction. Returns None if not parseable.

    Percent units (any "percent of X" or "% of X") -> value/100.
    Any other unit (including blanks) returns None.
    """
    v = parse_float(value)
    if v is None:
        return None
    u = _safe_str(unit)
    if not PAY_PCT_RE.search(u):
        return None
    # Clamp to [0,1]; some CAOs encode "100%" for full
    return max(0.0, min(1.0, v / 100.0))


# ---------------------------------------------------------------------------
# Statutory floors as a function of ingangsdatum (CAO effective date)
# ---------------------------------------------------------------------------
def statutory_floor(eff_date: date | None) -> dict:
    """Return statutory floor for each leave type as (weeks, rate) tuples.

    Each value is a list of (weeks, rate) segments that together form the
    statutory entitlement at the given date.

    Sources: Wet arbeid en zorg (WAZO), Wet invoering extra geboorteverlof
    (WIEG, 1 Jan 2019 and 1 Jul 2020), Wet betaald ouderschapsverlof
    (Aug 2022).
    """
    d = eff_date or date(2015, 1, 1)

    # Maternity: 16 weeks @ 100% (UWV-paid) throughout the window
    mat = [(16.0, 1.00)]

    # Adoption: 4 weeks @ 100% pre-2019; 6 weeks @ 100% from 1 Jan 2019
    if d >= date(2019, 1, 1):
        ado = [(6.0, 1.00)]
    else:
        ado = [(4.0, 1.00)]

    # Paternity / partner leave:
    # pre-2019: 2 days @ 100% (kraamverlof)
    # 2019-2020-07-01: 1 week (5 working days) @ 100% (WIEG)
    # 2020-07-01+: 1 week @ 100% + 5 weeks @ 70% (additional)
    if d >= date(2020, 7, 1):
        pat = [(1.0, 1.00), (5.0, 0.70)]
    elif d >= date(2019, 1, 1):
        pat = [(1.0, 1.00)]
    else:
        pat = [(2 * DAY, 1.00)]  # 2 working days

    # Parental (Hanna's correction, statutory_timeline.xlsx Leave tab, 2026-07-06):
    # pre-2009:       13 weeks (13x weekly hours) unpaid
    # 2009-2022-08:   26 weeks unpaid
    # 2022-08-02+:    9 weeks @ 70% + 17 weeks unpaid
    if d >= date(2022, 8, 2):
        par = [(9.0, 0.70), (17.0, 0.0)]
    elif d >= date(2009, 1, 1):
        par = [(26.0, 0.0)]
    else:
        par = [(13.0, 0.0)]

    return {"maternity": mat, "paternity": pat, "adoption": ado, "parental": par}


def fre_from_segments(segments):
    """Sum FRE-weeks across a list of (weeks, rate) segments."""
    return sum(w * r for w, r in segments)


def total_weeks_from_segments(segments):
    return sum(w for w, _ in segments)


# ---------------------------------------------------------------------------
# Per-row extraction
# ---------------------------------------------------------------------------
def extract_record(row: pd.Series) -> dict:
    """Compute FRE-weeks per leave type, both extracted-only and with-statutory."""
    def _s(x):
        if x is None or (isinstance(x, float) and pd.isna(x)):
            return ""
        return str(x).strip()

    # Parse the effective date for statutory floor selection. v2: the FILE DATE
    # (datum_kennisgeving = edition/publication date, fallback ingangsdatum) is
    # the time axis — a republished edition is measured against the law in force
    # when it was published. The CSV has mixed separators; normalise first.
    eff = None
    raw = _s(row.get("datum_kennisgeving")).replace("/", "-") or _s(row.get("ingangsdatum")).replace("/", "-")
    if raw:
        for fmt in ("%d-%m-%Y", "%Y-%m-%d"):
            try:
                eff = datetime.strptime(raw, fmt).date()
                break
            except ValueError:
                continue
    statutory = statutory_floor(eff)

    out = {}
    type_specs = {
        "maternity": dict(
            paid_v="leave_paid_maternity_value", paid_u="leave_paid_maternity_unit",
            pp_v="leave_partially_paid_maternity_value", pp_u="leave_partially_paid_maternity_unit",
            pp_rate_v="leave_partially_paid_maternity_pay_value", pp_rate_u="leave_partially_paid_maternity_pay_unit",
            unp_v="leave_unpaid_maternity_value", unp_u="leave_unpaid_maternity_unit",
        ),
        "paternity": dict(
            paid_v="leave_paid_paternity_value", paid_u="leave_paid_paternity_unit",
            pp_v="leave_partially_paid_paternity_value", pp_u="leave_partially_paid_paternity_unit",
            pp_rate_v="leave_partially_paid_paternity_pay_value", pp_rate_u="leave_partially_paid_paternity_pay_unit",
            unp_v="leave_unpaid_paternity_value", unp_u="leave_unpaid_paternity_unit",
        ),
        "adoption": dict(
            paid_v="leave_adoption_value", paid_u="leave_adoption_unit",
            pp_v=None, pp_u=None,
            pp_rate_v="leave_adoption_pay_value", pp_rate_u="leave_adoption_pay_unit",
            unp_v=None, unp_u=None,
        ),
        # Parental: paid_v / paid_u track parental_topup_pay (rate) — schema
        # only stores rate, not duration. Default duration = 9 (post Aug-2022)
        # else 0. Plus parental_unpaid for the unpaid portion.
        "parental": dict(
            paid_v=None, paid_u=None,
            pp_v=None, pp_u=None,
            pp_rate_v="leave_parental_topup_pay_value", pp_rate_u="leave_parental_topup_pay_unit",
            unp_v="leave_parental_unpaid_value", unp_u="leave_parental_unpaid_unit",
        ),
    }

    # Track per-leave-type pay-rate when the extractor stored a rate in the duration field
    paid_rate_override = {"maternity": None, "paternity": None, "adoption": None, "parental": None}

    for ltype, spec in type_specs.items():
        # --- paid duration ---
        paid_w = duration_to_weeks(row.get(spec["paid_v"]) if spec["paid_v"] else None,
                                   row.get(spec["paid_u"]) if spec["paid_u"] else None)

        # Defensive: the 'paid' field is sometimes used by the extractor to
        # store the pay RATE rather than duration (unit = "% of monthly salary").
        # Detect via a percent-style unit and impute statutory duration.
        if paid_w is None and spec.get("paid_v"):
            u = _safe_str(row.get(spec["paid_u"]))
            v = parse_float(row.get(spec["paid_v"]))
            if v is not None and PAY_PCT_RE.search(u):
                statutory_dur = total_weeks_from_segments(statutory[ltype])
                paid_w = statutory_dur
                paid_rate_override[ltype] = max(0.0, min(1.0, v / 100.0))

        # Default "paid" rate is 100% (schema definition: paid_maternity =
        # FULLY paid maternity leave; same for paternity).
        paid_rate = paid_rate_override[ltype] if paid_rate_override[ltype] is not None else 1.00

        # ADOPTION SPECIAL CASE: schema stores leave_adoption_value as TOTAL
        # duration (not necessarily paid) and leave_adoption_pay_value as the
        # rate that applies. So the "paid_rate" for adoption should come from
        # the pay field, not be hardcoded at 1.0.
        if ltype == "adoption":
            adoption_rate = pay_rate(row.get("leave_adoption_pay_value"),
                                     row.get("leave_adoption_pay_unit"))
            if adoption_rate is not None:
                paid_rate = adoption_rate
            elif paid_rate_override["adoption"] is None:
                # No explicit pay info -> assume statutory full-rate (UWV pays
                # adoption at 100% capped at max daily wage).
                paid_rate = 1.00

        # --- partially paid ---
        pp_w = duration_to_weeks(row.get(spec["pp_v"]) if spec["pp_v"] else None,
                                  row.get(spec["pp_u"]) if spec["pp_u"] else None) or 0.0
        pp_r = pay_rate(row.get(spec["pp_rate_v"]) if spec["pp_rate_v"] else None,
                        row.get(spec["pp_rate_u"]) if spec["pp_rate_u"] else None)

        # For parental: the rate field is the top-up rate; no companion duration field
        # exists in the schema, so apply the rate to the post-Aug-2022 9-week paid window.
        if ltype == "parental" and pp_r is not None and (paid_w or 0) == 0:
            if eff and eff >= date(2022, 8, 2):
                pp_w = 9.0
            else:
                pp_w = 0.0  # no statutory paid parental before Aug 2022

        # --- unpaid ---
        unp_w = duration_to_weeks(row.get(spec["unp_v"]) if spec["unp_v"] else None,
                                   row.get(spec["unp_u"]) if spec["unp_u"] else None) or 0.0
        unp_rate = 0.0

        # Extracted FRE-weeks for this leave type
        extr_paid = paid_w or 0.0
        extr_pp_rate = pp_r if pp_r is not None else 0.0
        extr_fre = extr_paid * paid_rate + pp_w * extr_pp_rate + unp_w * unp_rate
        extr_total_w = extr_paid + pp_w + unp_w

        # Statutory floor for this type
        stat_segments = statutory[ltype]
        stat_fre = fre_from_segments(stat_segments)
        stat_total_w = total_weeks_from_segments(stat_segments)

        # With-statutory: take max of (extracted, statutory) per dimension
        with_stat_fre = max(extr_fre, stat_fre)
        with_stat_total = max(extr_total_w, stat_total_w)
        imputed_fre = with_stat_fre > extr_fre + 1e-9

        out[f"{ltype}_paid_weeks"]      = round(extr_paid, 3)
        out[f"{ltype}_partial_weeks"]   = round(pp_w, 3)
        out[f"{ltype}_partial_rate"]    = round(extr_pp_rate, 3) if pp_w else None
        out[f"{ltype}_unpaid_weeks"]    = round(unp_w, 3)
        out[f"{ltype}_total_weeks_extr"]= round(extr_total_w, 3)
        out[f"{ltype}_fre_extr"]        = round(extr_fre, 3)
        out[f"{ltype}_total_weeks_stat"]= round(with_stat_total, 3)
        out[f"{ltype}_fre_stat"]        = round(with_stat_fre, 3)
        out[f"{ltype}_imputed"]         = imputed_fre

    out["fre_total_extracted"] = round(
        sum(out[f"{t}_fre_extr"] for t in type_specs.keys()), 3
    )
    out["fre_total_with_statutory"] = round(
        sum(out[f"{t}_fre_stat"] for t in type_specs.keys()), 3
    )
    out["duration_total_weeks_extracted"] = round(
        sum(out[f"{t}_total_weeks_extr"] for t in type_specs.keys()), 3
    )
    out["duration_total_weeks_with_statutory"] = round(
        sum(out[f"{t}_total_weeks_stat"] for t in type_specs.keys()), 3
    )
    out["any_imputed"] = any(out[f"{t}_imputed"] for t in type_specs.keys())

    # Quality flag: maternity-leave-vs-sick-pay confusion.
    # NL statutory maternity is 16 weeks @ 100% (UWV-paid); CAOs may add small
    # top-ups but real PAID maternity rarely exceeds ~25 weeks. A large
    # paid+partial maternity duration is almost certainly an extractor confusion
    # with the 104-week loondoorbetaling-bij-ziekte continuation (which is PAID).
    # NB: the test deliberately excludes *unpaid* weeks — legitimate long unpaid
    # leave exists (e.g. cao 429 grants verified "up to 1 year unpaid leave
    # following maternity"), and counting it here produced false positives.
    out["flag_maternity_overlong"] = (
        out["maternity_paid_weeks"] + out["maternity_partial_weeks"] > 30.0
    )
    # Similarly, no CAO realistically has >12 weeks of paid+partial paternity
    # above the statutory 1+5 week WIEG package (unpaid extensions excluded —
    # e.g. cao 1471's legitimate "4 wks paid + 2 mo unpaid").
    out["flag_paternity_overlong"] = (
        out["paternity_paid_weeks"] + out["paternity_partial_weeks"] > 12.0
    )
    # Adoption window-vs-duration confusion. Statutory adoption leave is ~6 wks
    # but may be TAKEN within a 26-week window around placement; the extractor
    # sometimes stored the window length as the leave duration. >=12 weeks of
    # adoption leave is implausible and likely the window, not the entitlement.
    out["flag_adoption_window"] = out["adoption_paid_weeks"] >= 12.0
    # WIEG paternity double-count: the 5-week aanvullend geboorteverlof
    # ("unpaid by employer, UWV pays 70%") sometimes logged in BOTH the
    # partially-paid and unpaid fields, counting the same weeks twice. Flag
    # when partial==unpaid (>0) — these inflate paternity total weeks.
    out["flag_paternity_double_count"] = (
        out["paternity_partial_weeks"] > 0.0
        and abs(out["paternity_partial_weeks"] - out["paternity_unpaid_weeks"]) < 1e-9
    )
    return out


def _cell_matches(current: str, expected: str) -> bool:
    """Lenient equality for the safety gate: blank==blank, numeric==numeric,
    else case-insensitive string match."""
    c = _safe_str(current); e = _safe_str(expected)
    if c == "" and e == "":
        return True
    try:
        return float(c.replace(",", ".")) == float(e.replace(",", "."))
    except ValueError:
        return c.lower() == e.lower()


def apply_source_corrections(df: pd.DataFrame) -> pd.DataFrame:
    """Apply the source-verified leave overlay (LEAVE_CORRECTIONS_CSV) in place.

    Each row names (id, field, expected_current, new_value). The edit is applied
    ONLY when the current cell equals expected_current (a safety gate matching
    apply_corrections.py); otherwise it is skipped and reported, so the overlay
    can never silently overwrite an unexpected value.
    """
    if not LEAVE_CORRECTIONS_CSV.exists():
        return df
    fd = os.open(str(LEAVE_CORRECTIONS_CSV), os.O_RDONLY)
    chunks = []
    while True:
        c = os.read(fd, 1 << 20)
        if not c:
            break
        chunks.append(c)
    os.close(fd)
    from io import BytesIO
    corr = pd.read_csv(BytesIO(b"".join(chunks)), sep=";", dtype=str).fillna("")
    df = df.copy()
    df["id"] = df["id"].astype(str)
    applied = skipped = already = 0
    for _, r in corr.iterrows():
        rid, field = str(r["id"]).strip(), str(r["field"]).strip()
        mask = df["id"] == rid
        if mask.sum() != 1 or field not in df.columns:
            print(f"  [corr SKIP] id={rid} field={field}: match={int(mask.sum())}")
            skipped += 1
            continue
        cur = df.loc[mask, field].iloc[0]
        # Already corrected (e.g. the fix is baked into corrected_dataset.csv via
        # apply_list.csv) -> no-op. This is the self-healing path: the overlay
        # only re-applies if the dataset has reverted to the pre-correction value.
        if _cell_matches(cur, r["new_value"]):
            already += 1
            continue
        if not _cell_matches(cur, r["expected_current"]):
            print(f"  [corr SKIP] id={rid} field={field}: current={cur!r} != expected={r['expected_current']!r}")
            skipped += 1
            continue
        df.loc[mask, field] = r["new_value"]
        applied += 1
    print(f"  source-corrections overlay: {applied} applied, {already} already-correct, "
          f"{skipped} skipped ({len(corr)} rows in {LEAVE_CORRECTIONS_CSV.name})")
    return df


def main():
    print(f"Reading {INPUT_CSV} ...")
    # Use os.read pathway to dodge the FUSE deadlock that hits Python's
    # high-level file readers on this particular mount.
    import os as _os
    fd = _os.open(str(INPUT_CSV), _os.O_RDONLY)
    chunks = []
    while True:
        c = _os.read(fd, 1 << 20)
        if not c:
            break
        chunks.append(c)
    _os.close(fd)
    from io import BytesIO
    df = pd.read_csv(BytesIO(b"".join(chunks)), sep=";", low_memory=False, dtype=str)
    print(f"  {len(df)} records, {df['cao_number'].nunique()} unique CAOs")

    df = apply_source_corrections(df)

    rows = []
    for _, r in df.iterrows():
        d = extract_record(r)
        d["cao_number"] = r["cao_number"]
        d["id"]         = r["id"]
        d["ingangsdatum"] = r["ingangsdatum"]
        d["file_name"]  = r["file_name"]
        # Document type: only full_cao_* docs carry complete leave info. Partial
        # amendments / supplements / annexes have blanks because they're partial,
        # NOT because the provision is statutory -> filling them with the floor
        # would be wrong. Flag (don't drop) so they can be filtered downstream.
        dt = _safe_str(r.get("general_document_type"))
        d["document_type"] = dt
        d["is_full_cao"]   = dt.startswith("full_cao")
        rows.append(d)
    out = pd.DataFrame(rows)

    # ----- v2 additions: file_date axis, doc_is_newest, pooled leave_z, coverage -----
    ken = df["datum_kennisgeving"].fillna("").map(il.parse_date)
    ing = df["ingangsdatum"].fillna("").map(il.parse_date)
    fdate = [k if k is not None else i for k, i in zip(ken, ing)]
    out["file_date"] = [d.isoformat() if d else "" for d in fdate]
    out["year"] = [d.year if d else None for d in fdate]
    out["pub_lag_months"] = [round((f - i).days / 30.44, 1) if (f is not None and i is not None) else None
                             for f, i in zip(fdate, ing)]
    out["term_group"] = df["cao_number"].astype(str).values + "|" + df["ingangsdatum"].astype(str).values
    out["_date"] = fdate
    out["_n_pop"] = (df.fillna("").astype(str) != "").sum(axis=1).values
    out["_idnum"] = pd.to_numeric(out["id"], errors="coerce")

    full = out[out["is_full_cao"]]
    s = full.sort_values(["cao_number", "_date", "_n_pop", "_idnum"])
    newest_idx = s.groupby("cao_number").tail(1).index
    out["doc_is_newest"] = out.index.isin(newest_idx)
    s = full.sort_values(["term_group", "_date", "_n_pop", "_idnum"])
    dedup_idx = s.groupby("term_group").tail(1).index
    dmask = pd.Series(out.index.isin(dedup_idx), index=out.index)

    # PER-TYPE scoring (2026-07-07): the 4 leave types are each an equal-weight +1 field, so a
    # CAO that enhances the most-bargained type (paternity, 76% enhance) gets its due. The old
    # summed-FRE let maternity's 16 wks dominate the total. leave_z = mean of the 4 per-type z's
    # (available-case); leave_gen01 = mean of the 4 per-type percentiles. Yardstick = one doc per
    # term_group, full-CAO only; all full-CAO docs scored. Params persisted for statutory_index.
    # maternity EXCLUDED from scoring: Dutch maternity is uniformly 16 wks @100% (WAZO), CAOs
    # don't vary it, so it has ~zero variance (no z) and its rank sits at the ceiling for
    # everyone (would inflate gen01). Kept as descriptive maternity_fre_stat. leave generosity
    # = the BARGAINED types.
    TYPES = ["paternity", "adoption", "parental"]
    params, typez, typepct = [], {}, {}
    for t in TYPES:
        x = pd.to_numeric(out[f"{t}_fre_stat"], errors="coerce").where(out["is_full_cao"])
        p = il.pooled_params(x, dmask)
        typez[t] = il.pooled_z(x, p)
        typepct[t] = il.pooled_pctile(x, dmask)          # +1 sign -> rank == generosity
        out[f"leave_{t}_z"] = typez[t].round(4)
        out[f"leave_{t}_prank"] = typepct[t].round(4)
        e = {"field": f"{t}_fre_stat", "variant": "full", "canonical": "fre_weeks", "sign": 1,
             "winsor_lo": "", "winsor_hi": "", "mu": "", "sd": "", "n": 0}
        if p: e.update({"winsor_lo": p["lo"], "winsor_hi": p["hi"], "mu": p["mu"], "sd": p["sd"], "n": p["n"]})
        params.append(e)
    Z = pd.DataFrame(typez); P = pd.DataFrame(typepct)
    out["leave_numeric_z"] = Z.mean(axis=1).round(4)               # magnitude track (was leave_z)
    out["leave_numeric_pctile"] = P.mean(axis=1).round(4)          # equal-range pctile (was leave_gen01)
    out["leave_numeric_rankpct"] = il.pooled_pctile(out["leave_numeric_z"], dmask).round(4)  # robustness (was leave_pctile)
    # companion: the summed-FRE total (interpretable "total paid-leave weeks") + extracted-only
    fre_stat = pd.to_numeric(out["fre_total_with_statutory"], errors="coerce").where(out["is_full_cao"])
    fre_extr = pd.to_numeric(out["fre_total_extracted"], errors="coerce").where(out["is_full_cao"])
    p_stat = il.pooled_params(fre_stat, dmask); p_extr = il.pooled_params(fre_extr, dmask)
    out["leave_numeric_z_fre_total"] = il.pooled_z(fre_stat, p_stat).round(4)   # summed-FRE companion
    out["leave_numeric_z_extr"] = il.pooled_z(fre_extr, p_extr).round(4)        # extracted-only (stability axis)
    for fld, canon, p in [("fre_total_with_statutory", "fre_weeks", p_stat),
                          ("fre_total_extracted", "fre_weeks", p_extr)]:
        e = {"field": fld, "variant": "full" if fld.endswith("statutory") else "raw",
             "canonical": canon, "sign": 1,
             "winsor_lo": "", "winsor_hi": "", "mu": "", "sd": "", "n": 0}
        if p: e.update({"winsor_lo": p["lo"], "winsor_hi": p["hi"], "mu": p["mu"], "sd": p["sd"], "n": p["n"]})
        params.append(e)
    il.save_params("leave", params)

    # leave coverage — share of the 12 GENEROSITY booleans (structural flags
    # *_statutory_ref / *_exceptions / hetero_present excluded, per convention)
    # NOTE (2026-07-08): the 3 sickness/care top-up booleans MOVED to absence coverage (they belong
    # to absence's sickpay/care concepts). leave coverage = the 9 parental/holiday-leave booleans.
    LEAVE_BOOLEANS = BOOLEANS   # module-level (below) so introspection (factor analysis) can find them
    present = pd.concat([df[b].fillna("").astype(str).str.strip().str.lower().eq("true")
                         for b in LEAVE_BOOLEANS], axis=1)
    out["leave_coverage"] = present.mean(axis=1).round(4).values
    out["leave_coverage_n"] = present.shape[1]
    cov_full = pd.to_numeric(out["leave_coverage"], errors="coerce").where(out["is_full_cao"])
    out["leave_coverage_z"] = il.pooled_z(cov_full, il.pooled_params(cov_full, dmask)).round(4)
    out["leave_coverage_pctile"] = il.pooled_pctile(cov_full, dmask).round(4)
    out = out.drop(columns=["_date", "_n_pop", "_idnum"])

    # Reorder: identifiers first, then headline indices, then components
    id_cols = ["cao_number", "id", "file_date", "ingangsdatum", "year", "file_name",
               "document_type", "is_full_cao", "doc_is_newest", "pub_lag_months", "term_group"]
    headline = [
        "leave_numeric_z", "leave_numeric_z_extr", "leave_numeric_z_fre_total", "leave_numeric_rankpct", "leave_numeric_pctile",
        "leave_paternity_z", "leave_adoption_z", "leave_parental_z",
        "leave_paternity_prank", "leave_adoption_prank", "leave_parental_prank",
        "leave_coverage", "leave_coverage_z", "leave_coverage_pctile", "leave_coverage_n",
        "fre_total_with_statutory", "fre_total_extracted",
        "duration_total_weeks_with_statutory", "duration_total_weeks_extracted",
        "any_imputed",
    ]
    components = [c for c in out.columns if c not in id_cols + headline]
    out = out[id_cols + headline + components]

    out.to_csv(OUTPUT_CSV, sep=";", index=False)
    print(f"Wrote {OUTPUT_CSV}  ({len(out)} rows, {len(out.columns)} cols)")

    # Quick diagnostics
    diag = pd.DataFrame({
        "metric": [
            "n_records",
            "n_unique_caos",
            "mean_fre_total_with_statutory",
            "median_fre_total_with_statutory",
            "min_fre_total_with_statutory",
            "max_fre_total_with_statutory",
            "mean_fre_total_extracted",
            "median_fre_total_extracted",
            "share_any_imputed",
            "share_zero_extracted_fre",
            "n_records_full_cao",
            "n_records_partial_excluded",
            "median_fre_total_with_statutory_full_cao",
        ],
        "value": [
            len(out),
            out["cao_number"].nunique(),
            round(out["fre_total_with_statutory"].mean(), 3),
            round(out["fre_total_with_statutory"].median(), 3),
            round(out["fre_total_with_statutory"].min(), 3),
            round(out["fre_total_with_statutory"].max(), 3),
            round(out["fre_total_extracted"].mean(), 3),
            round(out["fre_total_extracted"].median(), 3),
            round((out["any_imputed"]).mean(), 3),
            round((out["fre_total_extracted"] == 0).mean(), 3),
            int((out["is_full_cao"] == True).sum()),
            int((out["is_full_cao"] != True).sum()),
            round(out.loc[out["is_full_cao"] == True, "fre_total_with_statutory"].median(), 3),
        ],
    })
    diag.to_csv(OUTPUT_DIAGNOSTICS, sep=";", index=False)
    print(f"Wrote {OUTPUT_DIAGNOSTICS}")
    print("\nDiagnostics:")
    print(diag.to_string(index=False))


if __name__ == "__main__":
    main()
